#!/usr/bin/python3

import sys
import time


def factor(n):
    """Return a list of the prime factors for a natural number."""
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return (i, n // i)
    return None


if __name__ == "__main__":
    """Call main() if script invoked directly."""
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        exit()

    filename = sys.argv[1]
    try:
        with open(filename, 'r') as file:
            rows = file.readlines()
    except FileNotFoundError:
        print("Error: file '{filename}' not found")
        exit() 
    start = time.time()
    for row in rows:
        number = int(row.strip())
        factors = factor(number)
        if factors:
            print(f"{number}={factors[1]}*{factors[0]}")
        if time.time() - start > 60:
            print("Timeout")
            exit()
