#!/usr/bin/python3
"""Factor a list of numbers from a file."""

from math import sqrt
from sys import argv
import time


def open_read_file(file_name):
    """Read file and add to an array"""
    with open(file_name, "r", encoding="utf-8") as file:
        lines = file.readlines()
    return [int(line) for line in lines]


def find_and_times(n):
    """Factorize given number"""
    for i in range(1, n):
        if n == (n // i) * i:
            print(f"{n}={n // i}*{i}")
            break


def fac_list(ls):
    """Factorize every number in the list"""
    for num in ls:
        find_and_times(num)


if __name__ == "__main__":
    if len(argv) == 2:
        fac_list(open_read_file(argv[1]))
    else:
        print("Usage: {} <file>".format(argv[0]))
